name: CRuby Dev Builds
on:
  push:
    tags:
    - '*'
  schedule:
  - cron: '0 0 * * *'
jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
      if: github.event_name == 'schedule'
    - name: Create tag
      id: create_tag
      run: |
        if [[ "${{ github.event_name }}" == "schedule" ]]; then
          tag=builds-$(date +%Y%m%d-%H%M%S)
          git tag $tag
          git push origin $tag
        else
          tag=$(basename "${{ github.ref }}")
        fi
        echo "::set-output name=tag::$tag"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.create_tag.outputs.tag }}
        release_name: ${{ steps.create_tag.outputs.tag }}
        prerelease: true
    - name: Create artifact files
      run: |
        mkdir info
        echo "${{ steps.create_tag.outputs.tag }}" > info/tag
        echo "${{ steps.create_release.outputs.upload_url }}" > info/upload_url
    - uses: actions/upload-artifact@v1
      with:
        name: info
        path: info

  build:
    needs: [release]
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-16.04, ubuntu-18.04, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: info
    - name: Set upload_url
      id: release_info
      run: |
        upload_url=$(cat info/upload_url)
        echo "::set-output name=upload_url::$upload_url"

    - name: apt-get update on Ubuntu
      run: sudo apt-get update
      if: startsWith(matrix.os, 'ubuntu')
    - run: sudo apt-get install -y --no-install-recommends ruby bison libyaml-dev libgdbm-dev libreadline-dev libncurses5-dev
      if: startsWith(matrix.os, 'ubuntu')
    - run: brew install autoconf automake
      if: matrix.os == 'macos-latest'
    - name: Disable Firewall # Needed for TestSocket#test_udp_server in test-all
      if: matrix.os == 'macos-latest'
      run: |
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate

    - name: Clone Ruby
      uses: actions/checkout@v2
      with:
        repository: ruby/ruby

    # Build
    - run: chmod 755 $HOME # https://github.com/actions/virtual-environments/issues/267
    - run: mkdir -p ~/.rubies
    - run: autoconf
    - run: ./configure --prefix=$HOME/.rubies/ruby-head --disable-install-doc
      if: startsWith(matrix.os, 'ubuntu')
    - run: ./configure --prefix=$HOME/.rubies/ruby-head --disable-install-doc --with-openssl-dir=$(brew --prefix openssl@1.1) --with-readline-dir=$(brew --prefix readline)
      if: matrix.os == 'macos-latest'
    - run: make -j4
    - run: make install

    - name: Create archive
      run: tar czf ruby-head-${{ matrix.os }}.tar.gz -C ~/.rubies ruby-head

    # Test
    - run: ~/.rubies/ruby-head/bin/ruby --version
    - run: ~/.rubies/ruby-head/bin/ruby -ropen-uri -e 'puts open("https://rubygems.org/") { |f| f.read(1024) }'
    - run: make test-spec MSPECOPT=-j
    - run: make test-all TESTS="-j8"

    - name: Upload Built Ruby
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release_info.outputs.upload_url }}
        asset_path: ruby-head-${{ matrix.os }}.tar.gz
        asset_name: ruby-head-${{ matrix.os }}.tar.gz
        asset_content_type: application/gzip

  metadata:
    name: Update metadata about the last build
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: metadata
        fetch-depth: 0
    - uses: actions/download-artifact@v1
      with:
        name: info
    - name: Set tag
      id: tag_info
      run: |
        tag=$(cat info/tag)
        echo "::set-output name=tag::$tag"
    - run: |
        echo "${{ steps.tag_info.outputs.tag }}" > latest_build.tag
        git config user.name "GitHub Actions"
        git config user.email automated@automated.org
        git commit -a -m 'Update latest_build.tag'
        git push
